### PR TITLE
Make Caddy-compatible storage module

### PR DESCRIPTION
**Pull request by mholt**
Hi there @fillup! :wave:

We've had several requests from Caddy users that this be made available as a [Caddy storage module](https://caddyserver.com/docs/json/storage/). This allows Caddy to use DynamoDB to store certificates and things.

This approach turns the Storage type directly into a Caddy module. It doesn't break or affect any CertMagic-only users.

(If you prefer not to change the existing repo, we could always create a new wrapper type that is the Caddy module, leaving your existing Storage type unchanged. It's just a little more work to maintain.)

This allows DynamoDB storage to be easily used in Caddy like so:

```
{
	"storage": {
		"module": "dynamodb",
		"table": "Caddy"
	},
	...
}
```

or with the Caddyfile:

```
{
	storage dynamodb Caddy
}
...
```

optionally with extra settings:

```
{
	storage dynamodb Caddy {
		aws_endpoint myendpoint
		aws_region   us-east-foo
	}
}
...
```

If you want you can play with this using [xcaddy](https://github.com/caddyserver/xcaddy):

```
xcaddy run --config /path/to/your/config.json
```

Anyway, we have several users willing to try using this soon! Let me know if you think anything needs to be changed.

Thanks for writing this plugin!

### CODE REVIEW

**Comment by fillup** [comment]
@mholt this is awesome, thanks! I started working on the module but never finished it. It looks like the tests are failing to let me see if thats easy to fix or if one of the tests is no longer relevant or something. I'll get this merged asap. 

I actually ran into an issue with CertMagic in AWS that caused me to stall out until I could invest some more time. Perhaps you have advice. When running a service behind an Application Load Balancer, the ALB health check just attempts to make a TLS connection to the service by IP rather than hostname, so CertMagic doesn't know which cert to serve. Is there a config option to use a default cert for any TLS connections?

**Comment by mholt** [comment]
@fillup Yep, when clients omit the ServerName from a TLS handshake, you can tell CertMagic to serve up a certificate of your choice with the `DefaultServerName` option: https://github.com/caddyserver/certmagic/blob/0643091dc5705651fdc4c6b72043b5ffc521217e/config.go#L55-L58

**Comment by fillup** [comment]
Hi @mholt I merged this offline because I needed to merge it into `develop` first where I had some changes that had not yet been merged to `master`. I had to make a couple tweaks to get the builds and tests working again but they were minor and I don't think they'll affect the module work you did. Thanks again for this contribution, can you test again to see if your module works? I'll get these changes merged to master now too.

**Comment by mholt** [comment]
Sure, looks good to me!

**Pull request merged**
