### PR TITLE
fix issue with obtaining and releasing locks

### LINKED ISSUE #15: Possible bug in locking mechanism
Hello! We've received a few reports of certificates not renewing and they have similar symptoms:

- DynamoDB is the storage module
- Logs show that Caddy is trying to renew the certificate, but is waiting for a lock
- The "LOCK-..." key for that certificate is present, but never deleted or considered stale
- Even after deleting the LOCK- file, Caddy was still waiting for the lock (the `Lock()` method never returned)
- Restarting Caddy after deleting the lock file manually resolved the issue

I am not familiar with DynamoDB but I felt it was important to raise the issue, as this is where my investigation has led me so far.

Are you able to reproduce this behavior at all?

/cc @liran-co and @jackellis

### PR DESCRIPTION
**Pull request by cmawhorter**
fixes #15

first... this is the first time i've ever touched go.  some more experienced eyes would be much appreciated.

summary of changes:
- added dynamo for interacting with ddb, which is a PITA in the best of times
- removed separate `LOCK-*` ddb records. Lock is now a property of the main `Item` record. this means there is no longer a need to document TTL because there is no longer a need for it at all
- switched to the same "active locking" functionality that file storage supports. added idempotent ddb updates to support it
- decreased timeouts to better service _on demand_ generation. (is LockTimeout too low now though? 1m)
- added documentation about single region support

~~there is one breaking change: i renamed "Table" -> "TableName" without good reason.~~ the rename doesn't impact use. the name in caddy config remains "table".

i did have to make some small modifications to tests because some stuff was renamed or removed.  otherwise though tests are unchanged and pass. some additional tests would be great but i don't really know how to do that.

### CODE REVIEW

**Comment by fillup** [comment]
Hi @cmawhorter, thanks for the contribution. For your foray into Go you've done a good job. At a broader level though I'm still not clear how there is a problem with locks today. I have tests to confirm that existing but expired locks are removed and new locks are created. Are you able to duplicate or provide steps to prove there is a problem with the existing code? The 3rd party dynamo library you brought in provides some nice syntactic sugar but I'm not sure it's worth bringing a 3rd party library in just for that unless it's fixing something wrong with the core AWS SDK, especially for very simple queries/updates. 

I'm not saying _no_ to merging this, I just want to understand the problem better and how this solves it. 

Thanks!

**Comment by cmawhorter** [comment]
[this](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/howitworks-ttl.html) is the issue: 
image

a 48h guarantee on ttl deletion makes it a great option for record lifecycle but notsomuch for locking.  additionally that link says the problems will happen based on usage/capacity which means this will start failing at the worst possible time (when you're busy).

why dynamo? using ddb directly is a horrible and error-prone experience and that is doubly so when writing conditional updates, etc.  ddb just launched partiql which may fix this, but for now some kind of non-aws lib is pretty much a requirement of working with ddb in any way.

i could've kept the lock a separate record but i merged the two together 1) because i didn't realize how many _other_ non-cert records were also being written and 2) because it'd help people in advanced use cases *

* consider a ddb stream. if the lock is in the same record it means the lambda processing the stream could do something with that information. also global tables.

i've been using my changes while i'm testing and they seem to work ok so far. i've done minimal on-demand testing yet.  the one issue i've come across is there is an ocsp record for a wildcard that -- when it exists -- prevent usage of the wildcard.  i'm not sure if this is an issue with my changes or caddy itself.  the issue only happens when i'm using multiple caddy servers simultaneously.

**Comment by briskt** [comment]
@cmawhorter unfortunately, we have left this stale for a very long time. Can you give me an update on this? Are you still using this patch in your fork? I would be happy to merge it if I knew it was still helpful.

**Comment by cmawhorter** [comment]
i've been using it for a while now, but i think the two have diverged pretty significantly. feel free to grab whatever is useful and close this

**Comment by briskt** [comment]
We aren't using this library presently, but I am not sure whether other people are using it. Would you mind if I add a note to the README suggesting your fork? I might just archive this repo.

**Comment by briskt** [comment]
@fillup good to know. Thanks for bringing that to my attention.

**Pull request closed without merging**
